### ISSUE TITLE
Dynamic instruction coverage stats (--ujit-stats)

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#19]
We have to increase the proportion of instruction that gets executed in the JIT as opposed to the interpreter, to increase our "JIT coverage", so to speak. In order to do that, it would be really useful to have statistics such as the percentage of instructions executed by JIT over the total number of bytecode instructions executed.

I think it would also be very helpful to know  which instructions trigger exits to the interpreter and how often, and display a list sorted by decreasing frequency. That will help us target our efforts to increase coverage.

Additional thoughts:
- Maximize the readability of the --ujit-stats dump, make it human readable and easy to parse
- Make it so the output of the dump can easily be converted into a CSV file (space separated) or grabbed by a script

**Comment by XrXr** [comment]
59018fb1131a384d6d05b0b4f8bcc72292d7c02c gives a ratio of instructions that are ran in uJIT. We will make separate tickets for other statistics.
