### ISSUE TITLE
Slowdown in some benchmarks after Rust port of YJIT

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/ruby#284]
Looks like some of our benchmarks have slowed down a bit after the YJIT port, and others are noisy enough it's hard to tell. Worth exploring the definitely-slower ones to figure out what changed, and generally make sure code quality is where we want it.

This isn't shocking - we found a few subtle slowdowns during porting, makes sense there would be more left.

Looking at the speed-over-time deep dive (https://speed.yjit.org/timeline-deep), some benchmarks are slower. I'll compare 26th April at 7pm to 29th April at 9am below, so these slowdowns will vary a bit per-run. Benchmarks that seem to have gotten worse with Rust-YJIT are:

* chunky_png (5.5% slower)
* getivar (160% slower - but also noisy and a microbenchmark)
* nbody (28% slower)
* optcarrot (29% slower)
* rubykon (17.5% slower)

Possibly worse but hard to tell due to measurement error:

* hexapdf (0.3% slower)
* lee (1.3% slower)
* respond_to (3.5% slower and a microbenchmark)

Relevant links:

* Non-Rust results: https://speed.yjit.org/benchmarks/bench-2022-04-26-191744
* With-Rust results: https://speed.yjit.org/benchmarks/bench-2022-04-29-071352

**Comment by maximecb** [comment]
160% on getivar seems like a lot. Seems like it might make sense to start by trying to replicate that locally.

If the result can be reliably replicated locally, then there should be some obvious difference in the stats and the machine code. Should be relatively easy to trace since its a microbenchmark, and we could start from there 🤔

**Comment by noahgibbs** [comment]
Fair enough. Trying getivar first. Using the AWS instance, a pre-Rust build (v3_1_1) is getting 42ms on getivar, while head-of-master (63932ec33e720, 2nd May) is getting 109ms. So: very similar to the two builds checked above.

The disassembly of TheClass#get_value_loop in benchmarks/getivar.rb is massively different. It looks like the upshot is that pre-Rust it's 100% in YJIT, and post-Rust it's 0% in YJIT. So: far, far more side exits. The Rust disassembly is 7 blocks and the pre-Rust disassembly is 37, so something's very different.

Having a quick look at optcarrot, it's a similar story - 96% in YJIT pre-Rust, 82% in YJIT post-Rust. So that's a significant problem, and may well be the only problem.

I'll try and figure out what's going wrong from the disassembly.

**Comment by maximecb** [comment]
We must have broken something during the Rust port. Good thing you're looking at this because it could have gone unnoticed.

I think getivar is a good place to focus because it's relatively small. You could try simplifying the benchmark to try and find the simplest possible repro that shows a difference. Or you could try to determine which exit counter went up after the Rust port as that might give you a more direct hint about the cause.

**Comment by noahgibbs** [comment]
At the moment I'm just looking through the assembly. That's a bit much in many cases. But if we know we have a problem, it's probably good to check -- at least for the first 7 blocks, which they seem to basically have in common.

I'm having trouble interpreting the stats. Mostly they're fairly similar for both.

**Comment by noahgibbs** [comment]
This looks like it may be related to the changes in unknown types that we did for Rust YJIT.

Specifically, it looks like guard_two_fixnums is being called here. In pre-Rust YJIT, we'd see a "guard arg1 fixnum" comment with a test and jz/je instruction for the side exit (which isn't hit, and it all goes great.) In Rust YJIT, it looks like guard_two_fixnums is emitting an unconditional jump to the side exit.

That would either need to be because it thinks one of the arguments is a heap argument, or because it thinks one of the arguments is a specific (non-unknown) non-Fixnum object. Reference: https://github.com/ruby/ruby/blob/5c843a1a6e24aeabb3497065a362caf7b3e2d3b1/yjit/src/codegen.rs#L2253

This is in one of the lines "sum += @levar" where both are integers.

I'll add some comments locally to determine which case it's hitting.

**Comment by maximecb** [comment]
Good work tracking this down. Can you come up with a small repro?

Once we have a fix, maybe we can use John's testing framework to ensure that this doesn't exit.

**Comment by noahgibbs** [comment]
Sure. Here's a simplification of the code, with a printed disasm:

~~~
class TheClass
    def initialize
        @levar = 1
    end

    def get_value_loop
        sum = 0

        sum += @levar

        sum
    end
end

obj = TheClass.new

10.times { obj.get_value_loop } # Ensure the method has been jitted

puts RubyVM::YJIT.disasm(obj.method(:get_value_loop))
~~~

Run the code with a dev YJIT build ("--enable-yjit=dev"). In the disassembly, look at the start of the final block (block 4), in the #opt_plus section - it starts with an unconditional jump to a side exit, when it should instead start with a test and je (conditional side exit.)

This is a simple enough repro that it may be a lot of our speed problems - I expect we're seeing this a lot.

**Comment by noahgibbs** [comment]
Based on local debugging, looks like it thinks arg1 (in this case the instance variable) isn't a fixnum.

**Comment by maximecb** [comment]
Opened a PR for a fix here: https://github.com/ruby/ruby/pull/5876

**Comment by noahgibbs** [comment]
Ah, wait, definitely shouldn't close this yet - this was for all the benchmarks. I'll check the speed with this fix in place and see how the speed currently compares.

**Comment by noahgibbs** [comment]
After the most recent run (3rd May 7am) it looks like everything is back where it should be, perf-wise.

**Comment by maximecb** [comment]
Oh yeah! :)
