### ISSUE TITLE
YJIT: implement send (optimized calls)

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/ruby#305]
I've been working on this for a few workdays now. A tracking issue seems appropriate.

Send is implemented by CRuby as a special optimised function call type. As such, it doesn't push an extra stack frame. Given how much extra code a CRuby call-with-stack-frame generates, that's probably a significant optimisation.

The special-case call code for send in CRuby lives in vm_eval.c, mostly.

I have a branch that kinda-mostly works, but does not 100% fully work. And send is likely to be tricky. I've added a bunch of unit tests, but I'm *not* 100% sure they don't side-exit in weird ways that keep me from seeing all the bugs. I'll need to check that.

**Comment by noahgibbs** [comment]
Work notes on when CRuby does or does not push a frame for a method call:

I’m looking through CRuby’s vm_eval.c primarily.

The function vm_call0_body is the closest to our gen_send_general in most ways. It runs through the various types of method (ISEQ, cfunc, alias, etc.) and dispatches them appropriately.

It called send_internal, which actually makes the send happen - looks up the method from the string/symbol and dispatches to it with rb_call0.

For future exploration: vm_call0_cfunc_with_frame, which uses vm_push_frame and vm_pop_frame. Vm_call0_cfunc calls the _with_frame version unconditionally. So: cfunc always gets a frame. Makes sense.

rb_call0, which send dispatches to, eventually dispatches to vm_call0_cc in nearly all cases. That one just sets up a rb_calling_info structure and calls vm_call0_body, the first thing I mentioned here.

So: if you call send, send does *not* seem to set up a frame outside the normal one you’d get from a direct call. But for instance if you call a cfunc via send, it’s going to call through the layers down to vm_call0_cfunc_with_frame, which will push a frame. So: send does not *add* a frame in that case, but the normal frame you’d get for the call still happens.

public_send is just a cfunc, not a weird optimised thing, and *does* add an extra frame for its own cfunc, separate from the normal one. This is slightly inefficient but much easier to see and reason about, with less duplicated code. Other than (maybe?) an extra layer in the call stack I don’t think this would have any observable effect, and it’s presumably just fine.

The function we dispatch to, rb_f_send, calls send_internal_kw which just checks for kw args or not, sets a flag, and calls send_internal. That’s *not* going to push a send-specific frame, but it *is* going to push a frame if, e.g., you used send to call a cfunc.

I haven’t mentioned ISEQs yet. ISEQs don’t push a frame using the relatively simple cfunc-type setup. They call to a function in vm_insnhelper.c called vm_call_iseq_setup, which has a mazy set of sub-functions like vm_call_iseq_setup_normal_0start, which are presumably dispatched to depending on the details of the ISEQ and the call site.

Generally speaking it looks like an ISEQ call will *also* push a frame, as you’d expect it to, and will also use vm_push_frame like the cfuncs do.

So: calling rb_f_send should push a frame when needed, and it should not require an extra frame to be pushed. So that’s not the cause of the local-variable oddities I am observing.

**Comment by noahgibbs** [comment]
I have an in-progress branch with the current commits (somewhat messy): https://github.com/Shopify/ruby/tree/noah_yjit_send

**Comment by noahgibbs** [comment]
Code that demonstrates problems:

~~~
def internal_method
  puts "GOT HERE"
end
def jit_method
  send(:internal_method)
end
puts "Expect 0-args: GOT HERE (side effect)"
puts jit_method

def internal_method(*args)
  "#{args.size}##{args.join(",")}"
end

def jit_method
  send(:internal_method, *[1, 2, 3]) + "/" + send(:internal_method, 1, 2, 3)
end

puts "expect splatting: 3#1,2,3/3#1,2,3"
puts jit_method.inspect

def internal_method(**kw)
  "#{kw.size}##{kw.keys.map { |k| "#{k}:#{kw[k]}" }.join(",")}"
end

def jit_method
  send(:internal_method, **{ a: 1, b: 2 }) + "/" + send(:internal_method, a: 1, b: 2)
end

puts "expect keyword: 2#a:1,b:2/2#a:1,b:2"
puts jit_method.inspect

def internal_method(&b)
  "b:#{block_given? ? "y" : "n"}"
end

def jit_method
  b7 = proc { 7 }

  [
    send(:internal_method),
    send(:internal_method, &b7),
    send(:internal_method) { 7 },
    send(:internal_method, &nil),
  ].join("/")
end

puts "expect block args: b:n/b:y/b:y/b:n"
puts jit_method.inspect

def internal_method(a)
  "a:#{a}"
end

def jit_method
  send(:send, :internal_method, "arg")
end

puts "expect with arg: a:arg"
puts jit_method.inspect
~~~

Specifically: in the last line we're seeing "a:main" instead of "a:arg", which almost certainly is a stack-frame bug. The main object is being found rather than "arg", suggesting that we're not getting a stack-frame push we should that would let us see the argument. Or maybe the wrong thing is being pushed as an arg? Also possible.

We're also not seeing a slash in the "expect splatting" section - both sends are happening, the results are being added together, and the slash is being missed. So maybe we're returning to the wrong place in the code or something? It seems like a very weird bug to me.

Both of these are fine if run without YJIT. But if you run the code with "miniruby --yjit-call-threshold=1 ./bad.rb" you'll see the problem.

**Comment by noahgibbs** [comment]
If we modified the code for gen_send_cfunc to call rb_f_send, that would push an extra stack frame. That's usually not a problem (as public_send being different demonstrates), but it's good to avoid *any* visible differences from CRuby where we can. I assume that pushing an extra stack frame, in addition to being slower, would show up in C-level backtraces. We'd rather it didn't.

**Comment by noahgibbs** [comment]
Pairing with Maxime, we figured out I wasn't setting the PC and SP properly in the CFP frame data. So: needed a jit_prepare_method_call. Now the way I'm passing keyword arguments seems wrong - I grabbed the "put the keywords into a hash with build_kwhash" method from gen_send_cfunc. But it's not clear that that's working for rb_f_send. The passed argc seems wrong when there are keywords.

So: my next move is to look through vm_eval.c until I'm fairly certain how keyword data in calls is getting passed in, then make sure I'm passing my keywords properly.

**Comment by noahgibbs** [comment]
Okay, so for cfuncs it looks like if there are keywords (I *think* it's with any keywords, not just a keyword splat) there may be an extra argument hash for the keywords. And argc is increased by one for that hash. There's a related optimization for "if keywords are allowed but this call doesn't have any, remove the empty hash, decrement argc and don't set the 'has keywords' flag." So if there's a non-empty keyword hash, that would require argc to be one higher to compensate.
 
Reference for CRuby code to remove empty keyword hash: https://github.com/ruby/ruby/blob/7bab7883093df12048c4535b59b04e73f3b3b4ad/vm_eval.c#L129

I *think* the cfuncs are just winding up with the hash passed as a final arg, with argc being high enough to indicate that it exists. So I think they see a final hash arg and final keywords as identical. Not 100% sure on that. But it looks likely.

Checking on the ISEQ code... it's completely different. Not at all "just pass a final hash of keywords" like for cfuncs. That makes sense. It looks like it's mostly checking the callinfo for flags and setting things up from there.

But it *also* looks like argc is one higher for cfuncs with keywords, and it looks like that is *not* true for ISEQs being called. That probably means I'm a level of abstraction too low -- setting up cfunc-specific stuff when I should be at the "gen_send_general" level of abstraction. Maybe I don't need to handle keyword parameters at all and I just need to make sure the right flags are correct? I'll keep looking.

**Comment by noahgibbs** [comment]
ISEQs pretty clearly assume you have a bunch of keywords pushed onto the Ruby stack. In vm_insnhelper.c:vm_call_iseq_setup we pass SP - argc as the argv (that is, argv is on the Ruby stack), and the just-keywords part get copied into a new stack variable (see vm_callee_setup_arg, search for ALLOCA_N) and passed through to the ISEQ call as keywords.

Our own codegen.rs is similar -- for cfuncs we convert a bunch of keywords passed individually on the Ruby stack and replace it with a single Ruby hash. So okay, converting to a hash first is silly - the cfunc call code must necessarily do that. We want to create an *input* to the cfunc or ISEQ call code, so we need to create the "before" picture.

So: definitely don't need to build a kwarg hash. But just removing that code isn't enough by itself, I checked. We still get that arity error.

**Comment by noahgibbs** [comment]
Next question is presumably: how do ISEQs check arity, and why are we currently failing that check?

I've also put together a correct-but-scope-limited version of the change that just side-exits for send-with-keywords. But I'd rather get keywords working, so I'll keep at it for now.

**Comment by noahgibbs** [comment]
Hm. If the VM_CALL_KWARG flag is set (see vm_args.c:setup_parameters_complex) and the ISEQ allows keyword parameters we *do* subtract the number of keywords from argc. So: that's what it looks like when we call to an ISEQ. If there are M real args and N keyword parameters supplied, argc is initially N + M. No keyword hash added as a single argc param, though, that's a cfunc-only thing. Or maybe a cfunc-or-iseq-with-keyword-splat thing? But we don't currently JIT calls to send (or anything else) with a keyword splat, so we can ignore that for now.

However, we're currently failing the arity check with the YJIT-send code. So CRuby is not subtracting the number of keyword params when it should. Which probably means I'm not getting the "caller passed keywords" flag properly set in the calling_info structure. That would make sense -- I'm not passing or creating a calling_info or call_info structure. It gets reconstructed under the covers inside rb_f_send. So I'll figure out what it's checking when reconstructing it.

**Comment by noahgibbs** [comment]
Okay - when rb_f_send tries to tell if keywords are passed, rb_keyword_given_p() is returning false. That, in turn, checks the env flags (from cfp->ep):

~~~
return VM_ENV_FLAGS(cfp->ep, VM_FRAME_FLAG_CFRAME_KW) != 0
~~~

We *do* set the VM_FRAME_FLAG_CFRAME_KW when pushing a frame in gen_send_cfunc (only if there are keywords in the call). So maybe we need to set it here too? But we're not pushing a frame here. I'll try to figure out when/how CRuby sets it.

**Comment by noahgibbs** [comment]
Huh. Yeah, I'm only seeing CRuby set that flag when pushing a frame. But it's checking it in rb_f_send before it pushes the frame? Hrm.

I wonder if this is a leftover from rb_f_send being its own cfunc. So maybe they're assuming rb_f_send (or public send) *does* get a frame pushed first. If so, I may have to figure out how to drill down further, interface-wise, in order to supply the "yes, really, we're passing kwargs" parameter. While rb_f_send wants it set implicitly in the frame, a lot of the lower-level internal static funcs do not.

That's probably an argument for starting with send-without-keywords and making the with-keywords version be a different PR, though -- that's more likely to need to expose a currently-only-internal API inside vm_eval.c (or one of the other vm_*.c files).

**Comment by noahgibbs** [comment]
After having trouble with *both* kwargs and blocks, it looks like I'm going to need to expose something under vm_insnhelper.c -- vm_insnhelper keeps an entirely different parallel implementation of calling Ruby methods from vm_eval.c. Alan suggests that it's probably due to calling from C versus calling from Ruby, which sounds plausible to me. In any case, it seems like me using the vm_eval endpoints is just going to result in subtly different behaviour. Not only is there not an easy way for me to set the kwargs flag without pushing a frame (and we don't want to push a frame), but it looks like blocks work slightly differently with refinements, for reasons I'm having a lot of trouble figuring out.

So: my plan is to back off from "send" via vm_eval.c, and try an approach where I expose an endpoint in vm_insnhelper.c. The unit tests from the first attempt are merged upstream, so that'll help.

**Comment by jimmyhmiller** [comment]
Just thought I'd leave a note here that I've talked to Noah and am looking into this as well. I have an implementation working for very basic calls. But probably going to build some tooling to help me visualize the ruby stack better so I can make sure I am doing that manipulation properly.

**Comment by noahgibbs** [comment]
Seems like a good idea. Your approach seems likely to have better results than mine -- I was just going to avoid the side-exit, but your way would allow some actual optimisation. But it'll also want more testing and be generally a bit more involved.

**Comment by noahgibbs** [comment]
Hey @jimmyhmiller - is this done now?

**Comment by jimmyhmiller** [comment]
Yep got merged here https://github.com/ruby/ruby/pull/6488 

Thanks for checking up
