### ISSUE TITLE
YJIT: optimize `setinstancevariable` using object shapes

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#446]
Currently, for `setinstancevariable`, we always call a C function because of write barriers because we don't want to deal with the complexity of write barriers in YJIT. This is pretty slow and inefficient.

However, it's possible to know which generation an object is from based on header bits. We may also be able to know statically that write barriers are not necessary (i.e.: writing an integer property into an object).

We should be able to implement polymorphic inline caches for `setinstancevariable` in YJIT and make use of them when write barriers are not required. Potentially, we could start by checking at compile time if we know based on the type of the value being written that write barriers won't be necessary. We could also peek at the header bits of the object we're writing to and insert a dynamic guard. Only if we don't think write barriers won't be needed would we then generate code for a fast path using polymorphic inline caches. Otherwise we could rely on the old system using a C function call.

This is a bit more complex than what we currently have for `getinstancevariable`, but it seems manageable.

@tenderlove has expressed that he would like to tackle this after object shapes are upstreamed.

**Comment by maximecb** [comment]
Open PR here implementing this: https://github.com/ruby/ruby/pull/6767

**Comment by k0kubun** [comment]
merged it
