### ISSUE TITLE
Frequent illegal operation on Graviton in psych-load with low memory

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/ruby#459]
Reproduces frequently, but not every run, with:

    MIN_BENCH_ITRS=1 MIN_BENCH_TIME=0 WARMUP_ITRS=0 ruby --yjit-call-threshold=1 --yjit-exec-mem-size=1 -I ./harness benchmarks/psych-load/benchmark.rb

Reproduced with CRuby SHA ea278ddd92

**Comment by noahgibbs** [comment]
The problem doesn't reproduce without the --yjit-exec-mem-size=1 param. I was pretty sure, but it's good to check.

**Comment by noahgibbs** [comment]
It either doesn't repro or repros far less often on my M1 Mac laptop.

**Comment by XrXr** [comment]
I can't reproduce this on https://github.com/Shopify/ruby/commit/ea278ddd921bcafc3be2a79a7f0f68685e56da3b or later versions with  Graviton (a1.metal). Can you check again and post the crash log?

**Comment by noahgibbs** [comment]
Definitely not repro'ing with 41b0f641ef, including on the a1.metal benchmarking instance I've been using.

Clean rebuild with ea278dd, I'm still getting it. Not sure if that's worth our time to fix it since I'm not seeing it with later SHAs.

I'll attach the (printed to console) crash report, in case that's useful.

**Comment by noahgibbs** [comment]
[crash_report.txt](https://github.com/Shopify/ruby/files/10022345/crash_report.txt)

**Comment by noahgibbs** [comment]
Actually, given that I can't repro this with latest Ruby I'll just close it and make sure we monitor. I think we're at a point where I can just do a low-mem run on all the yjit-bench benchmarks as a regular thing, so if it pops up again, we should find it.
