### ISSUE TITLE
YJIT: all guard methods should update context's type info

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/ruby#460]
Right now we have various guard_object_is_array-type methods that do not update the context. Need to review all guard methods to make sure that if we do a guard, the context gets updated.

**Comment by maximecb** [comment]
Link to code for said guard methods: https://github.com/ruby/ruby/blob/9e067df76bda7384e8f3ddda2b348f3a742eb784/yjit/src/codegen.rs#L1295

And here, `guard_two_fixnums` is an example of another guard that does upgrade the types in the context: https://github.com/ruby/ruby/blob/9e067df76bda7384e8f3ddda2b348f3a742eb784/yjit/src/codegen.rs#L2286

**Comment by noahgibbs** [comment]
Previous, incomplete work: https://github.com/ruby/ruby/pull/6797

**Comment by maximecb** [comment]
> Previous, incomplete work: [ruby#6797](https://github.com/ruby/ruby/pull/6797)

Sorry Noah. I feel like I dropped the ball on this one. I wish there was an easy way to have our cake and eat it too (keep all the `str_concat` optimizations you made), particularly since we care so much about string concat performance. Maybe we can return to this in January, or find ways to merge some of the changes you worked on without touching `str_concat`.

**Comment by noahgibbs** [comment]
All good. You folks did great work on stability while I was away. This is a pretty small optimisation. But yeah, I could just add all the non-str_concat changes and leave a comment in str_concat saying why we don't do it the regular way. I'll plan on that, though after the 3.2.0 release. I'm OOO on the 20th/21st, and I don't think we want to sneak this in *right* before the deadline.

**Comment by noahgibbs** [comment]
Working on new draft PR: https://github.com/ruby/ruby/pull/7056

**Comment by maximecb** [comment]
Since the last time it was difficult to get everything to pass checks with one larger PR, I'm trying to merge the missing bits from our last attempt in this PR: https://github.com/ruby/ruby/pull/7489

**Comment by maximecb** [comment]
Looks like we've completed the work for this issue ✅ 🙂
