### ISSUE TITLE
YJIT: memory leak exposed by code GC

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#463]
I decided to run an experiment to check if we had any memory leaks in YJIT by running `railsbench` in a loop, triggering a code GC every iteration and checking the memory usage.  It looks like the memory usage does increase over time, and quite fast. The issue reproduces with both release and dev builds.

To be clear, I don't necessarily think that the code GC itself is causing the leak. The leak is probably somewhere else in YJIT, it's just that triggering code GC causes us to compile more code, which causes more Rust objects to be allocated. I suspect we maybe don't free branches, blocks (or other resources we use to keep track of invalidations?) correctly.

Either way, I'm not overly worried. This probably won't be too hard to fix 🤞🤞 , and we still have time before the 3.2 release.

I made a small modification to harness-continuous in `yjit-bench` to print the following data:
```
$ git diff harness-continuous 
diff --git a/harness-continuous/harness.rb b/harness-continuous/harness.rb
index 29a8aa7..49204a3 100644
--- a/harness-continuous/harness.rb
+++ b/harness-continuous/harness.rb
@@ -32,5 +32,23 @@ def run_benchmark(_)
     iterations = 1 if iterations.zero?
 
     start_time = end_time
+
+    if defined? RubyVM::YJIT
+      puts ""
+      puts "triggering code GC"
+      RubyVM::YJIT::code_gc
+
+      stats = RubyVM::YJIT::runtime_stats
+      if stats
+        puts "code_gc_count: #{stats[:code_gc_count]}"
+        puts "live_page_count: #{stats[:live_page_count]}"
+
+        if stats.key?(:yjit_alloc_size)
+          alloc_size = stats[:yjit_alloc_size].to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
+          puts "yjit_alloc_size: #{alloc_size} bytes"
+        end
+      end
+    end
+
   end
 end
```

Then we can monitor code GC and Rust alloc size for railsbench as follows:
```
$ ruby --yjit --yjit-stats -I./harness-continuous benchmarks/railsbench/benchmark.rb

triggering code GC
code_gc_count: 1
live_page_count: 2
yjit_alloc_size: 13,545,989 bytes
0.17841681128845283

triggering code GC
code_gc_count: 2
live_page_count: 2
yjit_alloc_size: 18,455,681 bytes
0.1921023275312122

triggering code GC
code_gc_count: 3
live_page_count: 2
yjit_alloc_size: 23,362,569 bytes
0.1877545012261644

...

triggering code GC
code_gc_count: 13
live_page_count: 2
yjit_alloc_size: 72,417,105 bytes
```

And it just keeps growing. I've checked with `ps` that the `rss` of the process will grow to 500MB+ (and presumably forever):
```
$ps x -o command,etime,rss,vsz | grep "\-\-yjit"
ruby --yjit --yj       02:41 544308 37022456
maximecb@Maximes-MBP-2 yjit % 
```

Tagging @XrXr @k0kubun (if you see this over the weekend, please enjoy your weekend, this can wait until next week).

**Comment by XrXr** [comment]
I've identified the source of the leak, however, fixing them seems a bit tricky. See https://github.com/shopify/ruby/commit/1093becfc61501e9a5d18d585a282e306a13dd82

**Comment by maximecb** [comment]
> I've identified the source of the leak, however, fixing them seems a bit tricky. See [1093bec](https://github.com/Shopify/ruby/commit/1093becfc61501e9a5d18d585a282e306a13dd82)

I'm glad you've identified the source of the biggest leak. Trying to understand the fix. I can see how it's tricky 😅

> The mechanics of this repro is that it sets up a stack frame that returns to a stub, and then invalidates the block containing said stub before returning. Since the change for (2) makes it so that we free branches when we invalidate the containing block, we end up calling `branch_stub_hit` with a branch pointer that's already freed.

> We intentionally didn't call free_block() because of a possible ractor race condition involving waking up to a freed branch inside branch_stub_hit().

I think we had assumed at the time that a future code GC would be able to come and free those blocks safely (left as homework for future us). Could that be a potential fix? Only free branch objects when the code GC decides that it's safe to free the containing blocks?

**Comment by k0kubun** [comment]
I'm also trying to understand the fix now 🙂

> we end up calling branch_stub_hit with a branch pointer that's already freed.

Is it possible to rewrite the code for branch_stub_hit's argument on invalidation so that the branch_stub_hit call will be safe? 

Or is it too late if it's already freed there? If so, I guess we'd need to conditionally decrement the counter by somehow detecting that case?

**Comment by XrXr** [comment]
> Is it possible to rewrite the code for branch_stub_hit's argument on invalidation so that the branch_stub_hit call will be safe?

That should be enough to make the script I included work, which is probably the highest risk case considering how ractors are not very popular. I think we'd need to also do the patching when the stub is hit normally since there could still be code on the stack returning to the call to branch_stub_hit. Basically we'd need to patch the code for the call in all situation where we lose access to the pointer of it. I guess that means all stub hits will be a little slower.

I've been trying a hack today where I search the iseq for a containing block with the same branch_ptr to decide liveness but it's got its own problems too and also doesn't solve the ractor issue.

> Only free branch objects when the code GC decides that it's safe to free the containing blocks?

I think that's the full solution, to delay freeing any block and branches until code GC decides they are not on stack anymore. That should handle the ractor issue as well. I guess the downside is we'd hold on to more memory to keep the metadata alive in-between code GC.

**Comment by maximecb** [comment]
> I think that's the full solution, to delay freeing any block and branches until code GC decides they are not on stack anymore. That should handle the ractor issue as well. I guess the downside is we'd hold on to more memory to keep the metadata alive in-between code GC.

Seems fairly ok to wait until code GC to collect this data. This solution has the benefit of being simple?

**Comment by XrXr** [comment]
Yeah, it's certainly better than the current situation where we never free them. 😅 
I'll try implementing it today.
