### ISSUE TITLE
YJIT: run our own Mastodon instance and federate it

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#464]
In the last YJIT team meeting, @jimmyhmiller suggested that we could potentially run our own Mastodon instance and federate it to get traffic. I quite like this idea because Mastodon is a large open source rails app, with real-world relevance. The best part though is that, as Jimmy pointed out, we could instrument this as much as we want without worrying about disrupting production.

There is currently an open PR on Mastodon to add Ruby 3.1 support: https://github.com/mastodon/mastodon/pull/21061

I'm trying to get attention from community members there so that the PR gets approval. If that can get merged, then I think upgrading to Ruby 3.2 would be a relatively small change, and we could even offer help to accelerate the process.

One tricky bit is that if we wanted a performance comparison against a baseline using the interpreter, we'd need two identical instances, which may be hard/impractical. However, we might be able to just compare our instance against its own past performance, and we might be able to track a number of useful stats, even if we can't easily compare against interpreter performance.

If we create such an instance, we could call it ruby social, or YJIT social or something like that, and run it on the cheapest GCP instance.

**Comment by matthewford** [comment]
I know the truffle Ruby team are also keen to get a performance baseline

**Comment by maximecb** [comment]
Will close this one for now since we currently have two production deployments and our hands are kind of full.
