### ISSUE TITLE
YJIT: things to wrap up for Ruby 3.2

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#465]
This is a list of things to do and wrap up in time for the Ruby 3.2 release  🎁🎄 
- [x] Fix memory leak bug https://github.com/Shopify/ruby/issues/463
- [x] Update default `--yjit-call-threshold` to 30 https://github.com/ruby/ruby/pull/6850
- [x] https://github.com/Shopify/ruby/issues/461
- [x] Complete https://github.com/Shopify/ruby/issues/446
- [x] Double-check message `ruby --yjit` prints when built without YJIT support
- [x] Update `yjit.md` and fix inaccurate/outdated information
- [x] Double-check CRuby `NEWS.md` for YJIT
- [x] Investigate continuous growth of object shapes count on SFR 🦖 
- [x] Update CRuby release notes for YJIT
  - Move closer to the top of the document
  - Brag more about performance and memory usage (provide specifics)
- [x] Create a performance graph for the CRuby release notes
- [x] Implement fix for pathological shapes growth case (transition to hash)
- [x] Fix ARM64 CI illegal instruction crash bug triggered by code GC https://bugs.ruby-lang.org/issues/19234
- [x] Post on Ruby core Slack, remind people to install `rustc` >= 1.58.0
- [x] Fix Zeitwerk YJIT bug: https://github.com/eileencodes/zeitwerk_yjit_repro
- [x] Make sure that Ruby head passes all checks on the Shopify Core CI with YJIT enabled
- [x] Re-enable Ractor tests for YJIT before the release (see https://github.com/ruby/ruby/commit/85f041c0c5cb3edf2bd062aa19020bde3b4cbc44 and https://github.com/ruby/ruby/commit/7b38853bc37a312b0543d402b334d4cc67be5aed)

If you think of anything else we need to wrap up or keep track of, please mention it in the comments :)

**Comment by k0kubun** [comment]
> Update default --yjit-call-threshold to 50, 75 or 100 (value TBD) based on SFR data

We've tested that 10 and 20 compile and free too many unneeded ISEQs, and 30, 40, 50, 100, and 200 don't (no significant difference in metrics between the latter numbers).

The turning point would be in between 20 and 30, but we'd probably want to use a round number, so maybe 30 if want the minimum round number, or 50 or 100 if 30 is not round enough? If you think 25 is also round, I can test that in the next deployment. At the same time, we might want to have some leeway from the explosion point too.

(Let me know if we want to use a separate issue for any discussion that is not about the TODO list itself)

**Comment by maximecb** [comment]
Sure, let's make it 30 :)

**Comment by k0kubun** [comment]
> Fix (probably YJIT-related) ractor bug: https://github.com/ruby/ruby/actions/runs/3575374374/jobs/6011846425

I talked with Koichi on Slack. Looking at [a Ractor test failure with YJIT](https://github.com/ruby/ruby/actions/runs/3603398545/jobs/6071549328#step:18:33), he said Ractor's implementation is probably bad and it needs to be reworked. He agreed to skip flaky tests for YJIT, so I pushed https://github.com/ruby/ruby/commit/85f041c0c5cb3edf2bd062aa19020bde3b4cbc44 and https://github.com/ruby/ruby/commit/7b38853bc37a312b0543d402b334d4cc67be5aed. Given that he plans to rework the implementation anyway and few people are using Ractors on production as of today, it's probably not a high priority for us to look into fixing it at this moment. WDYT?

**Comment by maximecb** [comment]
As long as we can remember to re-enable these tests before the release it should be ok.

**Comment by k0kubun** [comment]
OK, I'll re-enable them before the release. I'll update the TODO list as such.

**Comment by k0kubun** [comment]
> Re-enable Ractor tests for YJIT before the release

I guess we'll skip this in Ruby 3.2 and revisit it in 3.3? I could enable it during the release to make sure we at least randomly pass it with YJIT too if we want.

**Comment by maximecb** [comment]
> > Re-enable Ractor tests for YJIT before the release
> 
> I guess we'll skip this in Ruby 3.2 and revisit it in 3.3? I could enable it during the release to make sure we at least randomly pass it with YJIT too if we want.

The fact that the tests are disabled but only for YJIT makes me a bit uncomfortable, but unsure what to do given that the cause may be the ractor implementation itself. At least it's not all of the ractor tests though.

**Comment by k0kubun** [comment]
Okay, re-enabled the tests that were skipped only for YJIT https://github.com/ruby/ruby/commit/650a20a3e1205f47224a987676cdbad7d826d597.

**Comment by maximecb** [comment]
And it looks like we're all done with everything we needed to do this year for 3.2.

Well done team 👏 ❤️
