### ISSUE TITLE
Make offset and size of embedded/heap array length consistent

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#495]
Currently, the offset and size of the array length field is different for embedded and heap arrays.

In YJIT, we need to generate code to handle both branches, so we generate this sequence of instructions on x86:
```
  # get array length for embedded or heap
  0x10df40094: mov rdx, qword ptr [rcx]
  0x10df40097: and rdx, 0x3f8000
  0x10df4009e: sar rdx, 0xf
  0x10df400a2: test word ptr [rcx], 0x2000
  0x10df400aa: cmove rdx, qword ptr [rax + 0x10]
```

If the length was always at the same offset, this could be done with just a single instruction. This would be more efficient for both the interpreter and JITs.

This is already the case for strings:
```
  # get string length
  0x111f3008e: mov rax, qword ptr [rbx]
```

It could be nice if we were able to make this work. In an ideal case we would use 32-bits in the header for the length (same offset as the shape bits?) to avoid increasing the size of embedded arrays, but I realize this may be hard to achieve.

Tagging @peterzhu2118 @eightbitraptor and @tenderworks

**Comment by maximecb** [comment]
@peterzhu2118 do you have an opinion on the potential impact of this in terms of memory usage efficiency?

**Comment by peterzhu2118** [comment]
We should measure this, but I don't think it would be too big of an impact. Of course, it means that all the embedded arrays have one less in capacity.

I can take a look at this sometime next week, unless you're already looking into it 🙂

**Comment by maximecb** [comment]
Would like to have your opinion. How much capacity do embedded arrays currently have?

**Comment by peterzhu2118** [comment]
I think the biggest impact will be for the smallest arrays that live in the 40 byte size pool, which would result in embedded capacity of 3 elements down to 2 elements. It should be increasingly less noticeable for larger arrays. For example, the next size pool is 80 bytes, which would go from 8 embedded elements to 7 embedded elements.

**Comment by maximecb** [comment]
I guess it would make sense to benchmark such a change, to the extent that we can. The arrays will remain embedded even though they are in the next size pool though, correct?

**Comment by peterzhu2118** [comment]
Yes, it would mean that for size pool 40, 80, 160, 320, 640, the embedded capacities go from 3 -> 2, 8 -> 7, 18 -> 17, 38 -> 37, 78 -> 77, respectively.

**Comment by peterzhu2118** [comment]
I implemented this feature in this branch: https://github.com/Shopify/ruby/tree/pz-ary-len-combine

Unfortunately, the benchmark results are not great. There are no speedups. RSS is mostly the same except for hexapdf, which sees a huge increase in RSS. I looked into why hexapdf has such bad memory performance. It's because on master, 72k arrays are embedded while 75k arrays are heap allocated. However, on the branch only 38k arrays are embedded while 104k arrays are heap allocated.

```
-------------  -----------  ----------  ---------  -----------  ----------  ---------  -------------  --------------
bench          master (ms)  stddev (%)  RSS (MiB)  branch (ms)  stddev (%)  RSS (MiB)  master/branch  branch 1st itr
activerecord   147.1        0.4         54.5       148.6        0.1         54.3       0.99           0.99
hexapdf        2460.5       0.5         216.0      2510.9       0.8         282.8      0.98           0.97
liquid-c       64.7         1.5         39.9       65.1         1.5         39.4       0.99           1.00
liquid-render  162.5        1.1         36.2       164.2        1.1         36.3       0.99           0.99
mail           132.6        0.6         50.3       135.0        0.4         49.9       0.98           1.01
psych-load     2080.3       0.1         37.3       2105.9       0.1         37.0       0.99           0.99
railsbench     2012.5       0.7         106.1      2011.0       0.9         104.8      1.00           1.00
ruby-lsp       68.2         9.1         94.7       67.9         9.2         95.2       1.01           0.99
sequel         124.7        1.5         42.5       124.2        1.4         42.5       1.00           1.00
-------------  -----------  ----------  ---------  -----------  ----------  ---------  -------------  --------------
```

**Comment by maximecb** [comment]
Thanks for going through the trouble to implement and benchmark this Peter. Much appreciated 🙏

**Comment by k0kubun** [comment]
Given that it's motivated by YJIT's complicated code to fetch the length of an array, I feel it's more reasonable to evaluate the speed with YJIT that is modified using this. I have it [here](https://github.com/Shopify/ruby/tree/yjit-ary-len-combine), and the result was:

```
before: ruby 3.3.0dev (2023-03-22T14:07:26Z master e340eb2106) +YJIT [x86_64-linux]
last_commit=core_assertions.rb: Fix backward compatibility with pre 2.7
after: ruby 3.3.0dev (2023-03-22T22:04:00Z yjit-ary-len-combine 81ad10e315) +YJIT [x86_64-linux]

-------------  -----------  ----------  ---------  ----------  ----------  ---------  ------------  -------------
bench          before (ms)  stddev (%)  RSS (MiB)  after (ms)  stddev (%)  RSS (MiB)  before/after  after 1st itr
activerecord   65.5         0.5         63.4       65.6        0.6         63.0       1.00          1.00
hexapdf        1153.8       1.3         355.5      1138.3      1.3         362.0      1.01          1.01
liquid-c       32.1         3.1         46.9       30.9        3.3         47.0       1.04          1.07
liquid-render  58.5         3.1         43.5       57.7        3.5         43.7       1.01          1.01
mail           72.1         0.4         56.5       72.3        0.5         56.4       1.00          1.03
psych-load     993.2        0.2         41.8       989.2       0.1         42.1       1.00          1.00
railsbench     997.1        1.6         121.3      994.4       1.6         121.0      1.00          1.00
ruby-lsp       33.8         32.3        135.2      34.3        30.7        135.9      0.99          1.12
sequel         88.9         3.1         51.3       89.2        3.6         51.1       1.00          0.93
-------------  -----------  ----------  ---------  ----------  ----------  ---------  ------------  -------------
```

I can stably reproduce 3~4% speedup on liquid-c. Also the RSS impact on hexapdf was somehow not that bad with YJIT enabled.

**Comment by maximecb** [comment]
> I can stably reproduce 3~4% speedup on liquid-c. Also the RSS impact on hexapdf was somehow not that bad with YJIT enabled.

Hmmm, 3-4% is actually a pretty big difference.

How many bits are used by the array length when it's embedded in the header? If we could somehow always keep the array length in the header, and not lose one slot, not impact RSS, then this would always be a win.

**Comment by peterzhu2118** [comment]
It looks like there are 20 FL_USER bits. Arrays need 5 bits for other purposes. This means that there's 15 empty bits, which means that we can have lengths of at most 32k. I don't think that's enough for the most extreme cases.
