### ISSUE TITLE
Ultra-compact `Context` object encoding

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#498]
We're in the process of investigating a number of different context representations. Fundamentally, the problem that we want to solve is how to store more information in the context (i.e. the class and shape of self) while also using less memory. So far, the best that we have is context deduplication. One challenge with that is that it uses an external data structure, and we're not really sure how well it will work as we add more information to context (and contexts can become more unique/specific as a result).

So, here is a 6th possible idea (don't hate me 😅 ), which takes some inspiration from the PackedContext idea. IMO this idea has the benefit that it will predictably reduce memory usage.

Our starting point: the `Context` object currently takes up 38 bytes. It seems somewhat inefficient though. For one thing, we use two bytes for each `TempMapping`. So that's already 16 bytes just for TempMapping. In total, we use 32 bytes to encode `local_types`, `temp_types`, and temp_mapping`, we also use one extra byte to represent the type of self, so that's 33 bytes to represent type information.

Based on Kokubun's context dump on railsbench, we can see that the actual information that we store is actually [very sparse](https://gist.github.com/k0kubun/c1a5854e011db90d7e6efd73a6eda3b3).  OK then. How about we cut the amount of memory we use to represent type information from 33 bytes down to just 16 bytes? We can do this by designing a compact sparse encoding. This is similar to `PackedContext`, but we don't use slices, we use a raw array of 16 bytes, and we encode the contents of that ourself, without any dynamic memory allocation.

It should be pretty easy to represent some compact opcodes, with a variable-length payload.

Some potential opcodes:
- noop/end-of-input
- SetType
  - the opcode and the local/temp/self id can fit in one byte
  - use one more byte to represent the type
- MapToSelf (map temp to local)
  - single-byte opcode
- MapToLocal (map temp to self)
  - the opcode and local idx can fit in one single byte
- SetShape
  - the opcode and the local/temp/self id can fit in one byte
  - the shape ID can be encoded with 3 more bytes, so 4 bytes in total
- SetClass
  - the opcode and the local/temp/self id can fit in one byte
  - we may need up to 8 bytes for a class pointer
  - for common classes like Array, String, Hash, we'd want to encode these via SetType
  - for more compactness, we'd need a table of existing classes, we could then use a 16-bit class_idx
  - (shameless plug for pseudo-shapes, which would encode both the class and shape at the same time)

So with this, we get 16 bytes to encode as much type information as we can. This would likely be enough for most contexts. With the obvious caveat that class pointers would eat up most of that space very quickly if we do encode them... But with the exception of class pointers potentially being an issue, we should be able to encode something like 95% of the type information we currently do. We could also choose to be less spartan and allocate a generous 24 bytes for type info instead of the current 32 we currently use.

In   to this, `stack_size` and `sp_offset` both use 16-bit values. I think we could reduce those to be u8 and i8 if we add the restriction that YJIT will refuse to compile methods where the stack can grow to more than 128 (AFAIK CRuby tracks the maximum stack size of an ISEQ?). This would save two more bytes.

With these changes, we should be able to shrink `Context` down from 38 bytes to 19 bytes, or half of its previous size.

**Comment by maximecb** [comment]
Tagging @k0kubun and @jimmyhmiller

**Comment by k0kubun** [comment]
> IMO this idea has the benefit that it will predictably reduce memory usage.

Packed Context https://github.com/ruby/ruby/pull/7279 was 25.9 bytes per Context on average (including 8 bytes for the Box), and Context deduplication https://github.com/ruby/ruby/pull/7332 was _effectively_ 23.8 bytes per Context, so 16 bytes per Context would be an improvement. Packed Context could achieve a closer number if we make the length of the payload fixed and eliminate the 8 bytes for Box, but it's probably better to optimize the encoding as much as possible.

> This would likely be enough for most contexts.
>
> I think we could reduce those to be u8 and i8 if we add the restriction that YJIT will refuse to compile methods where the stack can grow to more than 128 (AFAIK CRuby tracks the maximum stack size of an ISEQ?).

We'd need to start thinking about the case that Context can't be encoded in 16/24 bytes and/or u8/i8 stack info.

We currently don't gracefully handle Context encoding failure (e.g. sp_offset/stack_size overflow), which just results in a crash today. Because half-baked `asm` is used in generated code even when `CantCompile` is returned, at least it's not safe to return `CantCompile` when u8 overflows in random places. Using 8 bits for them does seem like the right direction (at least railsbench didn't need 16 bits), but we need to modify how `CantCompile` is handled for it (or introduce something else).

> we could then use a 16-bit class_idx

Using a 16-bit index for pointers sounds like a good idea. 2^16 = 65536 seems enough.

---

I agree that it's probably better to use a variable-width encoding rather than an array/slice of fixed-length Rust enums. 

However, using a fixed-length array kind of shares the same downside as Context deduplication; we can't predict the impact of newly adding class/iseq pointers to Context. Using an external array for generating a 16-bit class_idx does mean the memory footprint is actually not limited to 16/24 bytes per Context, so we have to evaluate those ideas after actually adding those fields.

As long as our best solution has that kind of downside, we might want to "wait and see the impact of adding more information to the context" as you said at https://github.com/ruby/ruby/pull/7332#issuecomment-1435145878.

**Comment by maximecb** [comment]
> Packed Context [ruby#7279](https://github.com/ruby/ruby/pull/7279) was 25.9 bytes per Context on average (including 8 bytes for the Box), and Context deduplication [ruby#7332](https://github.com/ruby/ruby/pull/7332) was _effectively_ 23.8 bytes per Context, so 16 bytes per Context would be an improvement. Packed Context could achieve a closer number if we make the length of the payload fixed and eliminate the 8 bytes for Box, but it's probably better to optimize the encoding as much as possible.

Effective bytes per context are good metrics to have. Do you compute that based on total memory usage divided by the number of contexts? One thing I'm worried about when it comes to using box is that heap allocations don't come for free. There can be heap fragmentation (wasted space). The nice thing about this idea is that the payload lives inside of the Context object itself.

> We currently don't gracefully handle Context encoding failure (e.g. sp_offset/stack_size overflow), which just results in a crash today.

AFAIK ISEQs will tell us how much total stack space they can use, right? If so, we can just not compile ISEQs that use more than 128 temps with YJIT, and we should be guaranteed that sp_offset/stack_size will never overflow?

> We'd need to start thinking about the case that Context can't be encoded in 16/24 bytes

At the moment type information is optional. We use it for optimization, but we don't strictly need it. That would change if we were to say, add register allocation information to the context, however, or decide that we store the value of a constant in the context without actually writing it to the temp stack. Those pieces of information would be mandatory.

> However, using a fixed-length array kind of shares the same downside as Context deduplication; we can't predict the impact of newly adding class/iseq pointers to Context. Using an external array for generating a 16-bit class_idx does mean the memory footprint is actually not limited to 16/24 bytes per Context, so we have to evaluate those ideas after actually adding those fields.

IMO it's a lot more predictable than other approaches because we start from the assumption that we have a fixed number of bytes to encode the payload. I agree that having a side-table for pointers does make things a bit less predictable.

I think that minimally, before going to this idea, I could reduce the size of sp_offset and stack_size (if my assumption that we can know the max temp stack size from the ISEQ is correct), and I could also go and cut down the size of TempMapping from 2 bytes to 1 byte. So that would save us 10 bytes in total.

**Comment by k0kubun** [comment]
> Do you compute that based on total memory usage divided by the number of contexts? One thing I'm worried about when it comes to using box is that heap allocations don't come for free. There can be heap fragmentation (wasted space). The nice thing about this idea is that the payload lives inside of the Context object itself.

I did, for Context deduplication. I didn't for Packed Context. Doing that now, it's more like 27 bytes per Context. I agree that we should account for heap fragmentation when we discuss this.

> AFAIK ISEQs will tell us how much total stack space they can use, right? If so, we can just not compile ISEQs that use more than 128 temps with YJIT, and we should be guaranteed that sp_offset/stack_size will never overflow?

I think you're right. I was kind of worried about sp_offset being less predictable, but then you could calculate the limit based on the initial `ctx.sp_offset`.

> At the moment type information is optional. We use it for optimization, but we don't strictly need it. That would change if we were to say, add register allocation information to the context, however, or decide that we store the value of a constant in the context without actually writing it to the temp stack. Those pieces of information would be mandatory.

Okay. As long as mandatory parameters like sp_offset and stack_size fit in 16 bytes, it seems fine. I guess we could also try to push more important ones first and give up less important ones when it's saturated.

> I think that minimally, before going to this idea, I could reduce the size of sp_offset and stack_size (if my assumption that we can know the max temp stack size from the ISEQ is correct), and I could also go and cut down the size of TempMapping from 2 bytes to 1 byte.

Yeah, I was thinking about that too. Let's do it 🙂

**Comment by k0kubun** [comment]
I was interested in its impact, so I already gave a shot to the latter one https://github.com/ruby/ruby/pull/7368. 

~The code is as ugly as I anticipated, but the impact may be significant enough to justify it.~ I was originally thinking about https://github.com/Shopify/ruby/commit/8721fab2c540bab3958ca94226cbe31ed7b95098, but then I came up with https://github.com/Shopify/ruby/commit/5110167478d1318fd178f6fa46421c5c09f1e261. It still looks a bit ugly, but I think it's impactful and clean enough to be justified.

**Comment by k0kubun** [comment]
Well, I came up an idea to clean it up while keeping it a 1 byte, so I'll do it.

**Comment by maximecb** [comment]
Alan says that we can get the max number of stack temps with `ISEQ_BODY(iseq)->stack_max`

Another question is: if we limit ourselves to only JITting when `stack_max` < 128, so that we can never get `sp_offset` outside of the i8 range, are there corner cases where that we wouldn't cover that would materially reduce our production performance?

IIRC some instructions in CRuby can do things like splat arrays into the temp stack. I'm wondering how often it would happen that production code would write a large array of values on the temps stack, or something.

Maybe that's a moot point because YJIT already can't handle dynamic stack resizing?

Pinging @XrXr for input.

**Comment by XrXr** [comment]
I think the fact that `stack_max` is known at iseq building time implies that there is in general only limited dynamic stack resizing. There might be some cases with splats which YJIT needs to handle for method calls, but I don't think we'd be limited to what the context tells us there. It feels like we'd only need to copy VALUEs around, which is fine even when we need to go temporarily go outside of `sp_offset` to do it.
