### ISSUE TITLE
Investigate how `defined` is used in railsbench

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#50]
Should collect percentages for how `defined` is used in railsbench (from microjit-bench). Makes up ~5% of exits to the interpreter.

Is it mostly used for constants, for instance variables, or something else?

**Comment by tenderlove** [comment]
Finally got some stats for this, here is the table:

```
DEFINED_NIL -> 0
DEFINED_IVAR -> 794684
DEFINED_LVAR -> 0
DEFINED_GVAR -> 2
DEFINED_CVAR -> 100159
DEFINED_CONST -> 10203
DEFINED_METHOD -> 50493
DEFINED_YIELD -> 0
DEFINED_ZSUPER -> 10002
DEFINED_SELF -> 0
DEFINED_TRUE -> 0
DEFINED_FALSE -> 0
DEFINED_ASGN -> 0
DEFINED_EXPR -> 0
DEFINED_IVAR2 -> 0
DEFINED_REF -> 0
DEFINED_FUNC -> 80020
DEFINED_CONST_FROM -> 40
```

`DEFINED_IVAR` is the most popular, which I think is from memoization like `return @foo if defined?(@foo)`.

`DEFINED_CVAR` is pretty popular too, but what's interesting about this one is that I think nobody is actually writing `defined?(@@foo)`.  Using `||=` on a cvar will actually emit a defined instruction:

```
$ ./miniruby --dump=insns -e '@@foo ||= 1'
== disasm: #<ISeq:<main>@-e:1 (1,0)-(1,11)> (catch: FALSE)
0000 putnil                                                           (   1)[Li]
0001 defined                                class variable, :@@foo, false
0005 branchunless                           13
0007 getclassvariable                       :@@foo
0009 dup
0010 branchif                               17
0012 pop
0013 putobject_INT2FIX_1_
0014 dup
0015 setclassvariable                       :@@foo
0017 leave
```

**Comment by tenderlove** [comment]
I forgot to mention, I was testing against RailsBench.  Looks like optcarrot doesn't use `defined` at all.

**Comment by maximecb** [comment]
In terms of how difficult it would be to implement, DEFINED_IVAR and DEFINED_FUNC are pretty similar? Would knowing the class of an object be enough, or would we actually have to read the ivar on the object?

**Comment by tenderlove** [comment]
I haven't checked the implementation of `DEFINED_FUNC` yet, but I will.  `DEFINED_IVAR` is almost exactly the same as reading an ivar though.  I suspect `DEFINED_FUNC` is similar to `opt_send_without_block`, we just don't call the method. I'll investigate and update here with more details.

**Comment by maximecb** [comment]
But can we just check that the ivar is defined on the class, or do we actually have to read the object and make sure it's not Qundef/Qnil?

**Comment by tenderlove** [comment]
AFAICT, we actually have to read the object and check for Qundef (or non-existence of an extended table). Just because there's an entry in the index table on the class doesn't mean the ivar is "defined" on the particular object. 😩

```ruby
class Foo
  def initialize x
    @foo = 1 if x
  end

  def foo_defined?
    defined? @foo
  end
end

p Foo.new(true).foo_defined?

# @foo is now in the ivar index table on Foo, but below returns nil
p Foo.new(false).foo_defined?
```

**Comment by maximecb** [comment]
Ok cool. We're just going to have to factor out our implementation of getivar so that we can reuse it for this and for attr_reader.

**Comment by maximecb** [comment]
PS: yet another thing that Shapes will fix ;)

**Comment by maximecb** [comment]
Migrating to Shopify/yjit repo: https://github.com/Shopify/yjit
