### ISSUE TITLE
YJIT: delete or reuse old block after `defer_compilation`

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#500]
In railsbench, it seems that 32% of the blocks we create are actually from `defer_compilation`. It seems like there's a potential for some significant memory savings there if we could either delete old blocks after defer_compilation, or reuse/overwrite their memory (replace them with the new blocks).

I've gathered some stats on railsbench:
```
compiled_block_count:         20,472
compiled_branch_count:        35,805
defer_count:                   6,720
defer_empty_count:             1,391
```

It looks like 6.7% of blocks are generated by defer_compilation from a block that is empty. Presumably, it should be possible to delete such empty blocks. One potentially tricky aspects are that the chain_depth of the defer block and the new block won't be the same. We also need to remove deleted blocks from the version map. There might also be other complications I'm not thinking about.

We may be able to get more significant savings if we could somehow "overwrite" blocks prior to defer_compilation with the new block from after defer_compilation. I think this could be done by essentially "stretching" the new block to include the machine code from the old block before defer_compilation. This is more complex. It may not always be valid due to block invalidation assumptions... But it may be valid in some cases.

Maybe the easiest thing to do would be to start with the block deletion idea, which seems safer and simpler, and then see if we can, for some (most?) situations, go with the "overwrite" idea.

**Comment by k0kubun** [comment]
I haven't left a comment to explicitly say so, but I agree with the idea:

> Maybe the easiest thing to do would be to start with the block deletion idea, which seems safer and simpler, and then see if we can, for some (most?) situations, go with the "overwrite" idea.

Essentially, deleting a block is not safe when there's a thread that could still enter the block, but it seems fine if the block is a single jump-only and the entry to the block is eliminated by regenerate_branch during a branch stub hit while GVL is taken. It should be safe in terms of Code GC as well.

Rewriting a block is not safe when there's a thread that's in the middle of the block (i.e. the block is on stack). If a block is not leaf, it could be a problem, but it should be safe to rewrite blocks in some cases and maybe you could statically check that from ISEQ or some YJIT metadata. (edit: Well, even in the case that it's on stack and not leaf, if only an unrelated jump after the non-leaf operation is modified, maybe safe? If we patch blocks only in particular ways, maybe we could always modify existing blocks on defer_compilation...)

**Comment by XrXr** [comment]
We paired on this and found that a few cases where it's unsound to deallocate the empty blocks, because they keep alive branches that may be hit multiple times via recursion and/or threads. I've referenced this thread in a [commit](https://github.com/XrXr/ruby/commit/8ce02013292f72512e0dd232aaba7908a90ab13a).

**Comment by maximecb** [comment]
> We paired on this and found that a few cases where it's unsound to deallocate the empty blocks, because they keep alive branches that may be hit multiple times via recursion and/or threads. I've referenced this thread in a [commit](https://github.com/XrXr/ruby/commit/8ce02013292f72512e0dd232aaba7908a90ab13a).

It's really too bad that this is has turned out out to be a problem.

IIUC, when we're inside YJIT, there may be other threads/ractors that are just waiting to take the VM lock. These blocks could, in some rare situations, come read from the branch that we're trying to delete. These other threads are "waiting at the gate", so to speak. We don't actually know if anyone is actually waiting, or what they want, but we have to make the most pessimistic assumption possible. I feel like we've run into other such issues with ractors and `branch_stub_hit()` before.

If there was a way for us to, maybe through some lockless mechanism, somehow have all ractors tag the branch that has been hit when the VM lock is taken... We might have a way to know nobody is waiting for the same stub as us? I know this sort of thing could potentially get complicated and I'm not necessarily suggesting that would be a viable solution, but just dropping this idea out there because IIRC we did run into similar issues because of waiting threads in the past.

In general, my intuition tells me we're keeping around a lot of metadata that will never actually be needed again. For instance, like I was discussing with Alan the other day, we keep around a lot of contexts for branch stubs that will probably never ever be hit, just in case. That being said, maybe I am over-analyzing things, because in some sense, the code GC can obviously do a very good job at discarding all the code, and all the old metadata.

**Comment by XrXr** [comment]
> If there was a way for us to, maybe through some lockless mechanism, somehow have all ractors tag the branch that has been hit when the VM lock is taken... 

This sounds pretty close to the problem [hazard pointers](https://ieeexplore.ieee.org/document/1291819) solve. I don't understand them and no idea how complex an implementation would be.

The problem can happen even with single threaded code I think. We found that it crashes on railsbench, which should be strictly single threaded. I think it's caused by some sort of recursion, with `jit_return` pointing to a stub. This situation feels maybe more solvable than the multi-threaded case, but it still sounds challenging.

**Comment by maximecb** [comment]
I was just thinking. IIUC the problem we're trying to solve in the multithreaded case is that we can have multiple ractors touch the same `Branch`. Every ractor wants to mutate the `Branch` and `Block`, but that can be a problem because the first ractor to get the VM lock could modify the data, or delete the `Branch`, which then makes that branch pointer stale

However, we do have `stub_exit_code`, which we can use to exit from `branch_stub_hit` to the interpreter.

I was wondering, for the multithreaded code, if we could do something like:
- Try to acquire the VM lock, wait for all ractors to stop at the lock.
- One ractor gets the VM lock, generates code
- The ractors that didn't get the VM lock find out that someone else got the VM lock before them (is this feasible?)
  - These ractors will then take the `stub_exit_code` path to exit to the interpreter instead of compiling code
  - These ractors won't immediately exit to the interpreter, they wait until they get the VM lock too, but they don't touch the `Branch`

If that was somehow possible, then it would ensure that we don't run into a situations where multiple ractors touch the same `Branch` at the same time. One ractor gets the lock, the other ractors remain in a waiting state, but when the VM lock is released, they exit instead of compiling code. The tricky part is of course, how do you find out that someone else got the lock and you didn't.

**Comment by XrXr** [comment]
For `stub_exit_code`, we still need the context on the `Branch` to reconstruct interpreter state. And there are the other issues you mentioned, too.

**Comment by maximecb** [comment]
Closing this for now as it's not an immediate priority.

So far, it looks like this would be impractical to implement, and we've already made a lot of progress this year towards reducing memory usage.
