### ISSUE TITLE
YJIT: improve support for block arguments

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#524]
@noahgibbs created a new Rack routing benchmark. Looking at the YJIT stats, the overwhelming majority of the exits seem to be related to block arguments:
```
ratio_in_yjit:                 86.9%
avg_len_in_yjit:                38.9
Top-10 most frequent exit ops (100.0% of exits):
                      send:     10,359 (48.7%)
        getblockparamproxy:      9,972 (46.9%)
               invokeblock:        640 ( 3.0%)
               invokesuper:        240 ( 1.1%)
    opt_send_without_block:         23 ( 0.1%)
      opt_getconstant_path:          6 ( 0.0%)
                    opt_eq:          5 ( 0.0%)
                     leave:          4 ( 0.0%)
             setlocal_WC_0:          2 ( 0.0%)
                  opt_size:          1 ( 0.0%)
```

Send exit reasons:
```
method call exit reasons: 
      block_arg:     10,358 (99.9%)
    not_fixnums:          5 ( 0.0%)
    interrupted:          4 ( 0.0%)
```

I'm wondering how easy/hard it would be to improve the situation. @XrXr do you have an opinion wrt how much we are missing in order to support `block_arg` in send? How hard would this be to implement? Not saying that this is a priority or anything. Just trying to get a better idea of the current picture.

**Comment by XrXr** [comment]
So this is for calls that look like `foo(&obj)`. It looks like we have just a couple main cases left to handle --- when `obj` is symbol and when `obj` is some unknown object. There are cases where it's semantic to call `obj.to_proc` as part of the `&` process, but the no-conversation-necessary case (when `obj` is a `Symbol`/`Proc`) is probably most common and we can implement it by speculating.

I used `--yjit-trace-exits` on the benchmark and looked at the usage in Rack. It looks like it's hitting the case where `arg` is a `Proc`:

https://github.com/rack/rack/blob/8f5c885f7e0427b489174a55e6d88463173f22d2/lib/rack/builder.rb#L271-L275

In terms of effort required, I estimate that it'd take me about 3 days to handle the case Rack is using.

**Comment by maximecb** [comment]
> In terms of effort required, I estimate that it'd take me about 3 days to handle the case Rack is using.

How would it work? You'd need to convert the proc into something else?

**Comment by XrXr** [comment]
> How would it work? You'd need to convert the proc into something else?

We'd guard that it's a Proc. If the guard passes just setting it as a local variable should be enough. No conversion needed.

**Comment by maximecb** [comment]
This also seems to be a common exit cause on Core and in the lobsters benchmark. From Core stats:
```
Top-20 most frequent exit ops (99.9% of exits):
    opt_send_without_block:  170496134 (54.7%)

method call exit reasons: 
                      block_arg   29502043 (23.1%)
                  iseq_has_rest   27430102 (21.5%)
            args_splat_non_iseq   22853529 (17.9%)
            iseq_ruby2_keywords   18545055 (14.5%)
```

**Comment by noahgibbs** [comment]
It's a common enough reason for side exits that if one of those two cases (symbol vs some other object) was hard, it could make sense to just do the other. So even "fix one case, add a more specific failure metric for the other" could be very useful progress.

You *can* pass random objects in as a block and have Ruby convert them -- not a Proc or a Symbol, but like a String or Object or something. I've seen a random Ruby gem that adds "to_proc" as a method on String, and then you can pass a string like you would a symbol and have it convert. But I'll bet non-Symbol non-Proc is a rare case in prod, and a metric would be a great way to handle that until/unless we see it in the wild.

**Comment by maximecb** [comment]
Sure, it would certainly be nice to have more specific exit reasons.

Would also be nice to see the specific locations in the code that cause the exit in the lobsters benchmark so we can have an idea what it looks like at the Ruby level. Eileen & John worked on code for that.

@noahgibbs How close is lobsters from being usable by other team members? (even though it's not final yet)

**Comment by noahgibbs** [comment]
The branch is basically usable now. The Git history is a little messy and I'm still working on adding more routes.

**Comment by noahgibbs** [comment]
It's just in a branch called lobsters-bench in the yjit-bench repo.

**Comment by XrXr** [comment]
> I used `--yjit-trace-exits` on the benchmark and looked at the usage in Rack. It looks like it's hitting the case where `arg` is a `Proc`

We paired on support for this case and made https://github.com/ruby/ruby/pull/8117
It gives a ~2% boost to `ratio_in_yjit` on the Rack benchmark:

```
ratio_in_yjit:                 88.3%
avg_len_in_yjit:                44.0
Top-9 most frequent exit ops (100.0% of exits):
        getblockparamproxy:      9,972 (98.6%)
             setlocal_WC_0:         61 ( 0.6%)
               invokesuper:         56 ( 0.6%)

```

**Comment by maximecb** [comment]
Nice improvement :)

Any idea why getblockparamproxy is exiting? If we can tackle that one next then we should be much closer to 100% with the rack benchmark.

**Comment by XrXr** [comment]
Doh! Scratch that. There is actually no change to `ratio_in_yjit` due to the recent send fallback change; `send` is absent in the frequent exit list both before and after the patch. Comparing the now-poorly-named "method call exit reasons" list, it appears that the patch actually did very little:

```
ruby 3.3.0dev (2023-07-25T17:20:04Z gh/master e1104017e3) +YJIT [arm64-darwin22]
<snip>
method call exit reasons: 
                block_arg:     10,395 (99.8%)

ruby 3.3.0dev (2023-07-25T22:25:14Z yjit-block-arg b9ac41041d) +YJIT dev [arm64-darwin22]
<snip>
method call exit reasons: 
                block_arg:     10,058 (99.8%)
```

I'd falsely assumed that the ISeq cases are common when the Rack code I quoted was calling `new` which is a cfunc :/

**Comment by maximecb** [comment]
Whoops!

Calling new as a block? Can you paste the rack code snippet?

**Comment by XrXr** [comment]
https://github.com/rack/rack/blob/8f5c885f7e0427b489174a55e6d88463173f22d2/lib/rack/builder.rb#L271-L275

```
    def generate_map(default_app, mapping)
      mapped = default_app ? { '/' => default_app } : {}
      mapping.each { |r, b| mapped[r] = self.class.new(default_app, &b).to_app }
      URLMap.new(mapped)
    end
```

https://github.com/Shopify/ruby/issues/524#issuecomment-1633141580

Also, regarding `getblockparamproxy`, something weird is going on. The exit reason breakdown don't remotely sum to the total exit count:
```
 :gbpp_wb_required=>0,
 :gbpp_not_gc_guarded=>1,
 :gbpp_block_param_modified=>0,
 :gbpp_block_handler_not_none=>0,
 :gbpp_block_handler_not_iseq=>0,
```
More investigation needed.

**Comment by k0kubun** [comment]
We should probably split `block_arg` exit reasons. Like, you still don't have C method support in that PR, right? Also, I plan to file a PR to add a counter for the number of fallback calls today.

**Comment by maximecb** [comment]
> We should probably split block_arg exit reasons.

Agreed 👍 

> I plan to file a PR to add a counter for the number of fallback calls today

Great idea 👍

**Comment by XrXr** [comment]
So the block_arg PR is failing CI due to what seems to exhausting scratch registers, but I figured out the `getblockparamproxy` issue. https://github.com/ruby/ruby/pull/8124

New stats, a `0.6%` increase for ratio_in_yjit:
```
ratio_in_yjit:                 88.9%
avg_len_in_yjit:                44.3
Top-6 most frequent exit ops (100.0% of exits):
             setlocal_WC_0:         61 (43.0%)
               invokesuper:         56 (39.4%)
      opt_getconstant_path:         12 ( 8.5%)
```

**Comment by maximecb** [comment]
Nicely done.

Surprised we're only at 88.9% in this benchmark with so few exits left :O
