### ISSUE TITLE
YJIT: count machine-instructions executed in backend

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#526]
Sometimes we work on small optimizations and the performance results are hard to measure in terms of time, because the impact is less than 1 or 2%. There's also a challenge when it comes to keeping track of our performance results over time because we're sort of depending on cloud providers not upgrading their machines. Different CPU necessarily means different performance numbers.

I was thinking that, since we have control over the backend, it wouldn't be too hard to implement a new mode that counts CPU instructions executed. In the backend, we can increment an atomic counter based on how many machine instructions we emitted  in each block. It could be a bit tricky because we would have to account for branch instructions... But it does seem possible, and since we're counting, we could effectively ignore instructions executed in context switches (which perf can't do without a kernel patch).

The end goal would be, you pass a command-line switch, say `--yjit-count-insns` and the stats output then includes a total count of the number of machine instructions executed by YJIT in the backend. This would be a more stable and more sensitive metric than time. It could also help us track down sources of non-determinism. Another big upside is that we could have nice clean and stable graphs on speed.yjit.org (hopefully). We could start by implementing only x86 support for this mode.

The potential downsides:
- It's more sensitive than time but it doesn't account for scheduling. Less instructions isn't always better... Though it usually is, and I think it's generally a good thing to optimize for.
- May be more tricky to implement than I imagine because we need to take branches that leave blocks into account. The most naive way to implement this is to increment the counter at every instruction, but ideally we want to increment only when we reach a branch to avoid bloating the code size and impacting performance too much.
- Will bloat code size and blunt performance somewhat. Maybe up to something like 10-15%, so it should probably have its own command-line switch rather than automatically being enabled with `--yjit-stats`.

@XrXr and @k0kubun I'd like to get your opinion wrt difficulty and whether or not this is a dumb idea 😅

**Comment by k0kubun** [comment]
> I'd like to get your opinion wrt difficulty

I tried to implement a counter for memory / register stack operands before. It didn't work because these operands are used so often that some instructions added for the counter interfere with CPU flags for branching, etc. So I worry that a similar problem could happen if we implement this.

However, if we insert a counter only in safe locations, e.g. YARV insn boundary, it might work?

**Comment by maximecb** [comment]
I'm sure it's possible to make it work but we would need to account for flags, in addition to branches.

There are technically x86 instructions to push and pop flags to/from the C stack, which is one possible solution.

**Comment by XrXr** [comment]
I don't think the juice is worth the squeeze for this one. Asking the kernel for the instruction count for the whole process seems to be a better option. It's more holistic, just about as actionable, and doesn't require changes to YJIT. For just a more stable graph, maybe we could record CPU time (though that doesn't solve the issue of the hardware changing). Also, it seems the code size is already a fairly good proxy for the same info we can get out of counting, if we believe fewer is better.

I'm uncomfortable with the probe effect inherent with the idea, and how it creates pressure against what the backend could do in terms of reordering instructions.

**Comment by eregon** [comment]
What doesn't work with `perf`? AFAIK this is what we use for some benchmarks with GraalVM and it works well and is stable.
(but it cannot be the only metric measured as instructions don't relate exactly to time).

**Comment by maximecb** [comment]
> What doesn't work with perf?

AFAIK the perf instruction count also includes instructions executed by the kernel, so it's a bit noisy and imperfect. There's a way to fix that, but it requires installing a kernel patch that saves the right registers during context switches, which is not something we can easily install on a remote server.

That being said, maybe it is good enough even with that slight inaccuracy?

> Also, it seems the code size is already a fairly good proxy for the same info we can get out of counting, if we believe fewer is better.

Yes and no? There can often be a striking difference between a static count and a dynamic count of something.

You're making me realize there's a problem with what I suggested though. If we count instructions executed by YJIT, then that's going to trend up as we eliminate sources of side-exits... Even though we could be generating less efficient code. So that's definitely an argument for using perf instead.
