### ISSUE TITLE
Ideas to reduce YJIT's memory footprint

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#529]
We've done a lot this year to reduce YJIT's memory overhead, but Jean has made it clear that memory usage is still an issue on Core, particularly given that, since YJIT now compiles more code, we're also generating more metadata. As such, I think that optimizing memory usage should probably be one of our top priorities in order to produce a solid 3.3 release, along with frame outlining.

I think there are a number of things that we could do to optimize memory usage. I've collected a list with a few ideas below. I'm sure we can come up with more as well. Not guaranteed that all of these will pan out, but there are certainly many avenues we can investigate.

- Separating inline and outlined code into separate code pages. At the moment, we divide each code page into two halves for inline and outlined code. There's some inefficiency in that though, because it makes the assumption that inline and outlined code have approximately the same size, and pages are forced to end when either half becomes full. I think we might be able to have a system where we track separate pages for inline and outlined code. We would then jump to the next page when the current page is full, or when the inline and outlined pages become too far apart (IIRC ARM64 jump range is +- 1 MiB for conditional jumps?). The first step would probably be to quantify how much space we're currently wasting, but I think we could expect to save 5-10% of the code memory size, maybe more.
- Turn `VersionList` into a boxed array instead of a `Vec`. Should be OK given that most blocks have only one version.
- Could we move `gc_obj_offsets` from `Block` to `IseqPayload`? Do we need to store a separate list for each block? May also be worth re-examining the usefulness of each field in `Block`
  - Tried this in https://github.com/ruby/ruby/pull/8269 but ran into multiple segfaults. We may want to bite the bullet and migrate to a constant pool for better copy-on-write behavior instead?
- Could we delete `Block` objects we no longer need? Some blocks need to be kept around for invalidation, but if we had a way of deleting block objects that we know we will never touch again (whilst keeping their machine code around), this could result in major memory savings. We're previously attempted this in #500 but there might be other possible approaches
- ~Use `NonZeroU32` instead of `CodePtr` in Blocks and Branches~
- ~~[Ultra compact context encoding.](https://github.com/Shopify/ruby/issues/498:) I think we can probably shave 8+ bytes off of the context object~~
-  ~~We may be able to revisit warmup heuristics to prioritize compiling hotter functions (in relative terms) as opposed to just going by an absolute threshold. This may be particularly helpful for a large app such as core.~~

@XrXr @k0kubun

**Comment by XrXr** [comment]
Ref https://github.com/Shopify/ruby/issues/500 for the last time when we tried deleting `Block`s.

**Comment by k0kubun** [comment]
Looking at the previous thread https://github.com/Shopify/ruby/issues/484, I remembered we haven't finished migrating CodePtr from 64-bit addresses to 32-bit offsets yet https://github.com/ruby/ruby/pull/7408. We need to re-create the patch for the current master.

**Comment by maximecb** [comment]
Following Kokubun's 3.2 vs 3.2 experiments on SFR, it seems like Ruby 3.3 YJIT’s code size seems to be 1.8-2.0x larger than Ruby 3.2 YJIT.

This is surprising because IIRC we had ~80% coverage in 3.2. So, somehow, just closing that ~20% gap, we almost doubled the code size. It could be that there's some nonlinear dynamics at play (need to generate a lot more code to close the last few percent). I'm also wondering though if we could be generating a lot more stubs, guards and side-exits. I think we need to start tracking more accurately the inline vs outlined code size and how much wasted space there is when we switch to the next code page.

Might also be interesting to compute some kind of heat map on the lobsters benchmark. As in, for all the functions we do compile, how many times is each function executed in total, over the execution of the program. Then we create a bar chart with the bars sorted by total call frequencies. This would give us an idea what the distribution look like. We may able to do this on SFR as well, just a question of how to get the data out, but if we could have a list of all compiled functions, their inline and outline code size, and total call frequency, we may be able to produce some interesting plots.

**Comment by k0kubun** [comment]
> we need to start tracking more accurately the inline vs outlined code size

Was https://github.com/ruby/ruby/pull/7658 not enough for this?

**Comment by maximecb** [comment]
Just opened a PR to move `gc_obj_offsets` to the IseqPayload: https://github.com/ruby/ruby/pull/8269

**Comment by k0kubun** [comment]
Letting `SP` register point to `BP` (https://github.com/Shopify/ruby/issues/546) might be another thing we could explore, which should obviate `sp_offset` from `Context`. Because we can't restore the register using `cfp->sp` on `leave` instruction, we would need to execute one extra instruction after every `leave`, though.

**Comment by maximecb** [comment]
> Letting `SP` register point to `BP` ([Shopify/ruby#546](https://github.com/Shopify/ruby/issues/546)) might be another thing we could explore, which should obviate `sp_offset` from `Context`. Because we can't restore the register using `cfp->sp` on `leave` instruction, we would need to execute one extra instruction after every `leave`, though.

So we'd change the YJIT SP for a BP, and then, when we need to do a call or when doing a leave, we'd compute the CRuby SP value? Seems like it should probably be about equivalent in terms of efficiency. It's a lot of work to save one byte, but I'm open to the idea 👍 

With the PR I just opened (https://github.com/ruby/ruby/pull/8321), the Context struct will be 21 bytes, which is awkwardly not a multiple of 4 or 8.

**Comment by k0kubun** [comment]
> when we need to do a call or when doing a leave, we'd compute the CRuby SP value? Seems like it should probably be about equivalent in terms of efficiency.

I came up with an idea to make it efficient for JIT-to-JIT calls, but I'll need to think more about it for exits.

---

Speaking of stacks, I think we could also remove `stack_size` from `Context` because you can calculate `stack_size` from `BlockId` if you traverse ISEQ to the index you're going to compile. So, hopefully, we could remove both `sp_offset` and `stack_size` from `Context`.

**Comment by maximecb** [comment]
> I think we could also remove stack_size from Context because you can calculate stack_size from BlockId if you traverse ISEQ to the index you're going to compile

That's true, but it seems like a relatively expensive traversal though? Does YARV bytecode guarantee the property that the stack size is always the same at a given index in an ISEQ?

**Comment by k0kubun** [comment]
> it seems like a relatively expensive traversal though?

`IseqIdx` is u16, so up to 65536 instructions. It'd be worth checking how `30k_*` benchmarks do in the 1st itr before and after that change.

> Does YARV bytecode guarantee the property that the stack size is always the same at a given index in an ISEQ?

To my knowledge, it does.

**Comment by maximecb** [comment]
I rebased the yjit-dhat branch on master so we could get a more up to date memory profile: https://github.com/Shopify/ruby/issues/484

**Comment by maximecb** [comment]
Closing for now
