### ISSUE TITLE
RubyVM::YJIT.enabled? doesn't respect RUBYOPT="--yjit-pause"

### ISSUE THREAD

**Issue by intrip** [Shopify/ruby#545]
I noticed that if you boot Ruby with RUBYOPT="--yjit-pause" the output of "RubyVM::YJIT.enabled?" is always "true" even if you haven't called yet "RubyVM::YJIT.resume".

Example:

```bash
jacopo-37s-mb 3.3.0-preview2 ~ cat yjit.rb
#!/usr/bin/env ruby

puts "RUBY_DESCRIPTION: #{RUBY_DESCRIPTION}"
puts "RUBYOPT: #{ENV['RUBYOPT']}"
puts "YJIT enabled before resuming: #{RubyVM::YJIT.enabled?}"
puts "Resuming"
RubyVM::YJIT.resume
puts "YJIT enabled after resuming #{RubyVM::YJIT.enabled?}"
jacopo-37s-mb 3.3.0-preview2 ~ for rubyopt in "--yjit" "--yjit-pause" ""; do RUBYOPT=$rubyopt ruby yjit.rb; done
RUBY_DESCRIPTION: ruby 3.3.0preview2 (2023-09-14 master e50fcca9a7) +YJIT [arm64-darwin22]
RUBYOPT: --yjit
YJIT enabled before resuming: true
Resuming
YJIT enabled after resuming true
RUBY_DESCRIPTION: ruby 3.3.0preview2 (2023-09-14 master e50fcca9a7) +YJIT [arm64-darwin22]
RUBYOPT: --yjit-pause
YJIT enabled before resuming: true
Resuming
YJIT enabled after resuming true
RUBY_DESCRIPTION: ruby 3.3.0preview2 (2023-09-14 master e50fcca9a7) [arm64-darwin22]
RUBYOPT:
YJIT enabled before resuming: false
Resuming
YJIT enabled after resuming false
jacopo-37s-mb 3.3.0-preview2 ~
```

**Comment by maximecb** [comment]
We are in the process of removing `--yjit-pause`.

Future versions of Ruby will always have YJIT in paused mode when you don't specify `--yjit`, and you will be able to call `RubyVM::YJIT::enable` to start it.

**Comment by intrip** [comment]
Thanks @maximecb! We can close this one then.
I suppose `RubyVM::YJIT.enabled?` will return `false` until you call `RubyVM::YJIT::enable` correct?

**Comment by maximecb** [comment]
> Thanks @maximecb! We can close this one then. I suppose `RubyVM::YJIT.enabled?` will return `false` until you call `RubyVM::YJIT::enable` correct?

Yes that should be the case. You'll be able to test this in Ruby 3.3.0 preview3 or on Ruby head.
