### ISSUE TITLE
`leave` makes up 4.1% of exits on `railsbench` because of FINISH frames.

### ISSUE THREAD

**Issue by XrXr** [Shopify/ruby#63]

**Comment by XrXr** [comment]
https://github.com/Shopify/ruby/pull/64#issuecomment-790123647

**Comment by maximecb** [comment]
Nice work with the counters. They are proving useful.

> We could learn how to return from vm_exec_core by changing the scraper's example instruction or adding a new one.

OTOH maybe it's ok to exit to the interpreter for this? Hmmm.

Or how about this: we could create a new instruction that's just a `finish_frame` or `vm_exec_exit`, doesn't jump to anything else. Then we can directly jump to the handler for that when we want to exit and we know it's only going to do a return from `vm_exec_core` without any extraneous logic.

**Comment by maximecb** [comment]
We should create a jump equivalent to `call_ptr`, with a scratch register so that we can do a relative 32-bit jump when possible, and then we can likely do a nice predictable direct jump to the new exit instruction handler.

https://github.com/Shopify/ruby/blob/microjit/ujit_asm.c#L888

**Comment by maximecb** [comment]
Migrating to Shopify/yjit repo: https://github.com/Shopify/yjit
